global:
  resolve_timeout: 5m

route:
  receiver: slack-sls-bot
  group_by: ["alertname", "mode"]
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 2h

receivers:
  - name: slack-sls-bot
    slack_configs:
      - api_url: https://hooks.slack.com/services/REEMPLAZA/ESTE/WEBHOOK
        channel: "#sls-alertas"
        username: "sls-bot-alerts"
        icon_emoji: ":robot_face:"
        send_resolved: true
        title: "[{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }}"
        text: |-
          *Alert:* {{ .CommonAnnotations.description }}
          *Mode:* {{ .GroupLabels.mode }}
          *Labels:* {{ .CommonLabels | toJson }}
          *Starts:* {{ .StartsAt }}
          *Ends:* {{ .EndsAt }}

templates:
  - "/etc/alertmanager/templates/*.tmpl"
