global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/rules/prometheus_rules.yml

scrape_configs:
  - job_name: "sls_bot"
    static_configs:
      - targets:
          - "${SLS_PROM_TARGET_HOST:-host.docker.internal}:${SLS_PROM_TARGET_PORT:-8880}"
